watchfrr: Rename watchquagga -> watchfrr
Signed-off-by: Donald Sharp <sharpd@cumulusnetworks.com>

diff --git a/tools/quagga b/tools/quagga
--- a/tools/quagga
+++ b/tools/quagga
@@ -20,7 +20,7 @@ V_PATH=/var/run/quagga
 
 # Local Daemon selection may be done by using /etc/quagga/daemons.
 # See /usr/share/doc/quagga/README.Debian.gz for further information.
-# Keep zebra first and do not list watchquagga!
+# Keep zebra first and do not list watchfrr!
 DAEMONS="zebra bgpd ripd ripngd ospfd ospf6d isisd babeld pimd"
 MAX_INSTANCES=5
 RELOAD_SCRIPT=/usr/lib/quagga/quagga-reload.py
@@ -79,7 +79,7 @@ check_daemon()
 
         # vtysh_enable has no config file nor binary so skip check.
         # (Not sure why vtysh_enable is in this list but does not hurt)
-        if [ $1 != "watchquagga" -a $1 != "vtysh_enable" ]; then
+        if [ $1 != "watchfrr" -a $1 != "vtysh_enable" ]; then
           # check for daemon binary
           if [ ! -x "$D_PATH/$1" ]; then return 1; fi
 
@@ -102,29 +102,29 @@ check_daemon()
 start()
 {
        ulimit -n $MAX_FDS
-        if [ "$1" = "watchquagga" ]; then
+        if [ "$1" = "watchfrr" ]; then
 
-           # We may need to restart watchquagga if new daemons are added and/or
+           # We may need to restart watchfrr if new daemons are added and/or
            # removed
            if started "$1" ; then
-               stop watchquagga
+               stop watchfrr
            else
-               # Echo only once. watchquagga is printed in the stop above
+               # Echo only once. watchfrr is printed in the stop above
                echo -n " $1"
            fi
 
-           if [ -e /var/run/quagga/watchquagga.started ] ; then
-             rm /var/run/quagga/watchquagga.started
+           if [ -e /var/run/quagga/watchfrr.started ] ; then
+             rm /var/run/quagga/watchfrr.started
            fi
             ${SSD} \
                 --start \
                 --pidfile=`pidfile $1` \
                 --exec "$D_PATH/$1" \
                 -- \
-                "${watchquagga_options[@]}"
+                "${watchfrr_options[@]}"
             for i in `seq 1 10`;
             do
-              if [ -e /var/run/quagga/watchquagga.started ] ; then
+              if [ -e /var/run/quagga/watchfrr.started ] ; then
 		  break
               else
                   sleep 1
@@ -203,7 +203,7 @@ stop()
 # Converts values from /etc/quagga/daemons to all-numeric values.
 convert_daemon_prios()
 {
-        for name in $DAEMONS zebra vtysh_enable watchquagga_enable; do
+        for name in $DAEMONS zebra vtysh_enable watchfrr_enable; do
           # First, assign the value set by the user to $value
           eval value=\${${name}:0:3}
 
@@ -224,8 +224,8 @@ convert_daemon_prios()
         done
 }
 
-# Starts watchquagga for all wanted daemons.
-start_watchquagga()
+# Starts watchfrr for all wanted daemons.
+start_watchfrr()
 {
     local daemon_name
     local daemon_prio
@@ -233,14 +233,14 @@ start_watchquagga()
     local daemon_inst
 
     # Start the monitor daemon only if desired.
-    if [ 0 -eq "$watchquagga_enable" ]; then
+    if [ 0 -eq "$watchfrr_enable" ]; then
         return
     fi
 
     # Check variable type
-    if ! declare -p watchquagga_options | grep -q '^declare \-a'; then
+    if ! declare -p watchfrr_options | grep -q '^declare \-a'; then
       echo
-      echo "ERROR: The variable watchquagga_options from /etc/quagga/debian.cnf must be a BASH array!"
+      echo "ERROR: The variable watchfrr_options from /etc/quagga/debian.cnf must be a BASH array!"
       echo "ERROR: Please convert config file and restart!"
       exit 1
     fi
@@ -256,13 +256,13 @@ start_watchquagga()
                  eval "inst_disable=\${${daemon_name}_${inst}}"
                  if [ -z ${inst_disable} ] || [ ${inst_disable} != 0 ]; then
                      if check_daemon $daemon_name $inst; then
-                         watchquagga_options+=("${daemon_name}-${inst}")
+                         watchfrr_options+=("${daemon_name}-${inst}")
                      fi
                  fi
              done
           else
               if check_daemon $daemon_name; then
-                  watchquagga_options+=($daemon_name)
+                  watchfrr_options+=($daemon_name)
               fi
            fi
            found_one=1
@@ -272,16 +272,16 @@ start_watchquagga()
     # Start if at least one daemon is activated.
     if [ $found_one -eq 1 ]; then
       echo -n "Starting Quagga monitor daemon:"
-      start watchquagga
+      start watchfrr
       echo "."
     fi
 }
 
-# Stopps watchquagga.
-stop_watchquagga()
+# Stopps watchfrr.
+stop_watchfrr()
 {
     echo -n "Stopping Quagga monitor daemon:"
-    stop watchquagga
+    stop watchfrr
     echo "."
 }
 
@@ -509,10 +509,10 @@ case "$1" in
 
         # Start all daemons
         cd $C_PATH/
-        if [ "$2" != "watchquagga" ]; then
+        if [ "$2" != "watchfrr" ]; then
           start_prio 10 $dmn
         fi
-        start_watchquagga
+        start_watchfrr
         vtysh_b
         ;;
 
@@ -525,8 +525,8 @@ case "$1" in
 
     stop|0)
         # Stop all daemons at level '0' or 'stop'
-        stop_watchquagga
-        if [ "$dmn" != "watchquagga" ]; then
+        stop_watchfrr
+        if [ "$dmn" != "watchfrr" ]; then
          [ -n "${dmn}" ] && eval "${dmn/-/_}=0"
           stop_prio 0 $dmn
         fi
@@ -536,7 +536,7 @@ case "$1" in
           ip route flush proto zebra
        else
          [ -n "$dmn" ] && eval "${dmn/-/_}=0"
-         start_watchquagga
+         start_watchfrr
         fi
         ;;
 
