redhat: Disallow reload function for unsupported systems
Before the change, a reload triggered a restart if the python reload script wasn't installed or for non-integrated configs
With this change, the reload is rejected with an error in this case (and suggests the installation of the python script package)

Signed-off-by: Martin Winter <mwinter@opensourcerouting.org>

diff --git a/redhat/frr.init b/redhat/frr.init
--- a/redhat/frr.init
+++ b/redhat/frr.init
@@ -524,15 +524,13 @@ case "$1" in
     reload)
         # Just apply the commands that have changed, no restart necessary
         if [ ! -x "$RELOAD_SCRIPT" ]; then
-            echo "frr-reload script not installed - Executing full restart instead"
-            $0 restart
-            exit $?
+            echo "frr-reload - reload not supported. Use restart or install frr-pythontools package"
+            exit 1
         fi
         NEW_CONFIG_FILE="${2:-$C_PATH/frr.conf}"
         if [ ! -r $NEW_CONFIG_FILE ]; then
-            echo "Unable to read configuration file $NEW_CONFIG_FILE. Only supporting integrated config - Executing full restart instead"
-            $0 restart
-            exit $?
+            echo "Unable to read configuration file $NEW_CONFIG_FILE. Only supporting integrated config"
+            exit 1
         fi
         echo "Applying only incremental changes to running configuration from frr.conf"
         "$RELOAD_SCRIPT" --reload /etc/frr/frr.conf
